default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: month_money_development

test:
  <<: *default
  database: month_money_test

production:
  <<: *default
  database: <%= Rails.application.credentials.database %>
  username: <%= Rails.application.credentials.username %>
  password: <%= Rails.application.credentials.password %>

